language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
#  - pip install codecov

script: 
  - python setup.py install
#  - coverage run tests.py
#script: pytest
#after_success:
#  - codecov
