language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

script: python setup.py install
# command to run tests
#script: pytest
